server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plat?tinyInt1isBit=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driverclassName: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    #初始化大小
#    initialSize: 5
#    #最小连接数
#    minIdle: 5
#    #最大连接数
#    maxActive: 20
#    #连接等待超时时间
#    maxWait: 60000
#    #配置隔多久进行一次检测(检测可以关闭的空闲连接)，检测需要关闭的空闲连接，单位是毫秒
#    timeBetweenEvictionRunsMillis: 60000
#    #配置连接在池中的最小生存时间
#    minEvictableIdleTimeMillis: 300000
#    #校验sql、oracle配置，如果不配置validationQuery，则下面三项无效
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    # 打开PSCache，并且指定每个连接上PSCache的大小
#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 20
#    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#    filters: stat,wall,slf4j
#    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#    connectionProperties:
#      druid:
#      stat:
#      mergeSql: true
#      slowSqlMillis: 5000
    #合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat=true
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20